export const verbsData = [
    { infinitive: "beginnen", prateritum: "begann", partizip2: "begonnen", auxiliary: "haben", translation: "починати" },
    { infinitive: "bieten", prateritum: "bot", partizip2: "geboten", auxiliary: "haben", translation: "пропонувати" },
    { infinitive: "bitten", prateritum: "bat", partizip2: "gebeten", auxiliary: "haben", translation: "просити" },
    { infinitive: "bleiben", prateritum: "blieb", partizip2: "geblieben", auxiliary: "sein", translation: "залишатися" },
    { infinitive: "bringen", prateritum: "brachte", partizip2: "gebracht", auxiliary: "haben", translation: "принести, привезти" },
    { infinitive: "denken", prateritum: "dachte", partizip2: "gedacht", auxiliary: "haben", translation: "думати" },
    { infinitive: "empfehlen", prateritum: "empfahl", partizip2: "empfohlen", auxiliary: "haben", translation: "радити" },
    { infinitive: "essen", prateritum: "aß", partizip2: "gegessen", auxiliary: "haben", translation: "їсти" },
    { infinitive: "fahren", prateritum: "fuhr", partizip2: "gefahren", auxiliary: "sein", translation: "їхати" },
    { infinitive: "fallen", prateritum: "fiel", partizip2: "gefallen", auxiliary: "sein", translation: "падати" },
    { infinitive: "fangen", prateritum: "fing", partizip2: "gefangen", auxiliary: "haben", translation: "ловити" },
    { infinitive: "finden", prateritum: "fand", partizip2: "gefunden", auxiliary: "haben", translation: "знаходити" },
    { infinitive: "fliegen", prateritum: "flog", partizip2: "geflogen", auxiliary: "sein", translation: "літати" },
    { infinitive: "geben", prateritum: "gab", partizip2: "gegeben", auxiliary: "haben", translation: "давати" },
    { infinitive: "gehen", prateritum: "ging", partizip2: "gegangen", auxiliary: "sein", translation: "йти" },
    { infinitive: "haben", prateritum: "hatte", partizip2: "gehabt", auxiliary: "haben", translation: "мати" },
    { infinitive: "halten", prateritum: "hielt", partizip2: "gehalten", auxiliary: "haben", translation: "тримати" },
    { infinitive: "helfen", prateritum: "half", partizip2: "geholfen", auxiliary: "haben", translation: "допомагати" },
    { infinitive: "kennen", prateritum: "kannte", partizip2: "gekannt", auxiliary: "haben", translation: "знати" },
    { infinitive: "kommen", prateritum: "kam", partizip2: "gekommen", auxiliary: "sein", translation: "приходити" },
    { infinitive: "laufen", prateritum: "lief", partizip2: "gelaufen", auxiliary: "sein", translation: "бігти" },
    { infinitive: "lesen", prateritum: "las", partizip2: "gelesen", auxiliary: "haben", translation: "читати" },
    { infinitive: "liegen", prateritum: "lag", partizip2: "gelegen", auxiliary: "haben", translation: "лежати" },
    { infinitive: "nehmen", prateritum: "nahm", partizip2: "genommen", auxiliary: "haben", translation: "брати" },
    { infinitive: "nennen", prateritum: "nannte", partizip2: "genannt", auxiliary: "haben", translation: "давати ім'я" },
    { infinitive: "raten", prateritum: "riet", partizip2: "geraten", auxiliary: "haben", translation: "радити" },
    { infinitive: "rufen", prateritum: "rief", partizip2: "gerufen", auxiliary: "haben", translation: "кликати" },
    { infinitive: "schlafen", prateritum: "schlief", partizip2: "geschlafen", auxiliary: "haben", translation: "спати" },
    { infinitive: "schlagen", prateritum: "schlug", partizip2: "geschlagen", auxiliary: "haben", translation: "бити" },
    { infinitive: "schließen", prateritum: "schloss", partizip2: "geschlossen", auxiliary: "haben", translation: "закривати" },
    { infinitive: "schreiben", prateritum: "schrieb", partizip2: "geschrieben", auxiliary: "haben", translation: "писати" },
    { infinitive: "schwimmen", prateritum: "schwamm", partizip2: "geschwommen", auxiliary: "sein", translation: "плавати" },
    { infinitive: "sehen", prateritum: "sah", partizip2: "gesehen", auxiliary: "haben", translation: "бачити" },
    { infinitive: "sein", prateritum: "war", partizip2: "gewesen", auxiliary: "sein", translation: "бути" },
    { infinitive: "singen", prateritum: "sang", partizip2: "gesungen", auxiliary: "haben", translation: "співати" },
    { infinitive: "sitzen", prateritum: "saß", partizip2: "gesessen", auxiliary: "haben", translation: "сидіти" },
    { infinitive: "sprechen", prateritum: "sprach", partizip2: "gesprochen", auxiliary: "haben", translation: "розмовляти" },
    { infinitive: "springen", prateritum: "sprang", partizip2: "gesprungen", auxiliary: "sein", translation: "стрибати" },
    { infinitive: "stehen", prateritum: "stand", partizip2: "gestanden", auxiliary: "haben", translation: "стояти" },
    { infinitive: "steigen", prateritum: "stieg", partizip2: "gestiegen", auxiliary: "sein", translation: "підніматися" },
    { infinitive: "sterben", prateritum: "starb", partizip2: "gestorben", auxiliary: "sein", translation: "померти" },
    { infinitive: "tragen", prateritum: "trug", partizip2: "getragen", auxiliary: "haben", translation: "носить" },
    { infinitive: "treffen", prateritum: "traf", partizip2: "getroffen", auxiliary: "haben", translation: "зустрічати" },
    { infinitive: "treten", prateritum: "trat", partizip2: "getreten", auxiliary: "haben", translation: "ступати" },
    { infinitive: "trinken", prateritum: "trank", partizip2: "getrunken", auxiliary: "haben", translation: "пити" },
    { infinitive: "tun", prateritum: "tat", partizip2: "getan", auxiliary: "haben", translation: "робити" },
    { infinitive: "vergessen", prateritum: "vergaß", partizip2: "vergessen", auxiliary: "haben", translation: "забувати" },
    { infinitive: "verlieren", prateritum: "verlor", partizip2: "verloren", auxiliary: "haben", translation: "губити, програти" },
    { infinitive: "verstehen", prateritum: "verstand", partizip2: "verstanden", auxiliary: "haben", translation: "розуміти" },
    { infinitive: "wachsen", prateritum: "wuchs", partizip2: "gewachsen", auxiliary: "sein", translation: "виростати" },
    { infinitive: "waschen", prateritum: "wusch", partizip2: "gewaschen", auxiliary: "haben", translation: "мити" },
    { infinitive: "wissen", prateritum: "wusste", partizip2: "gewusst", auxiliary: "haben", translation: "знати" },
    { infinitive: "werden", prateritum: "wurde", partizip2: "geworden", auxiliary: "sein", translation: "ставати" },
    { infinitive: "ziehen", prateritum: "zog", partizip2: "gezogen", auxiliary: "haben", translation: "тягнути" },
    { infinitive: "abfahren", prateritum: "fuhr ab", partizip2: "abgefahren", auxiliary: "sein", translation: "від'їжджати" },
    { infinitive: "abfliegen", prateritum: "flog ab", partizip2: "abgeflogen", auxiliary: "sein", translation: "вилітати" },
    { infinitive: "abgeben", prateritum: "gab ab", partizip2: "abgegeben", auxiliary: "haben", translation: "здавати, віддавати" },
    { infinitive: "abschließen", prateritum: "schloss ab", partizip2: "abgeschlossen", auxiliary: "haben", translation: "замикати, завершувати" },
    { infinitive: "anbieten", prateritum: "bot an", partizip2: "angeboten", auxiliary: "haben", translation: "пропонувати" },
    { infinitive: "anfangen", prateritum: "fing an", partizip2: "angefangen", auxiliary: "haben", translation: "починати" },
    { infinitive: "ankommen", prateritum: "kam an", partizip2: "angekommen", auxiliary: "sein", translation: "прибувати" },
    { infinitive: "anrufen", prateritum: "rief an", partizip2: "angerufen", auxiliary: "haben", translation: "дзвонити (по телефону)" },
    { infinitive: "ansehen", prateritum: "sah an", partizip2: "angesehen", auxiliary: "haben", translation: "дивитися на" },
    { infinitive: "anziehen", prateritum: "zog an", partizip2: "angezogen", auxiliary: "haben", translation: "одягати" },
    { infinitive: "aufstehen", prateritum: "stand auf", partizip2: "aufgestanden", auxiliary: "sein", translation: "вставати" },
    { infinitive: "ausgeben", prateritum: "gab aus", partizip2: "ausgegeben", auxiliary: "haben", translation: "витрачати (гроші)" },
    { infinitive: "ausgehen", prateritum: "ging aus", partizip2: "ausgegangen", auxiliary: "sein", translation: "виходити в світ, гаснути" },
    { infinitive: "aussehen", prateritum: "sah aus", partizip2: "ausgesehen", auxiliary: "haben", translation: "мати вигляд" },
    { infinitive: "aussteigen", prateritum: "stieg aus", partizip2: "ausgestiegen", auxiliary: "sein", translation: "виходити з транспорту" },
    { infinitive: "ausziehen", prateritum: "zog aus", partizip2: "ausgezogen", auxiliary: "sein", translation: "виїжджати, роздягатися" },
    { infinitive: "backen", prateritum: "buk / backte", partizip2: "gebacken", auxiliary: "haben", translation: "пекти" },
    { infinitive: "behalten", prateritum: "behielt", partizip2: "behalten", auxiliary: "haben", translation: "утримувати, зберігати" },
    { infinitive: "bekommen", prateritum: "bekam", partizip2: "bekommen", auxiliary: "haben", translation: "отримувати" },
    { infinitive: "bewerben", prateritum: "bewarb", partizip2: "beworben", auxiliary: "haben", translation: "подавати заяву (на роботу)" },
    { infinitive: "biegen", prateritum: "bog", partizip2: "gebogen", auxiliary: "haben", translation: "гнути, повертати" },
    { infinitive: "braten", prateritum: "briet", partizip2: "gebraten", auxiliary: "haben", translation: "смажити" },
    { infinitive: "brechen", prateritum: "brach", partizip2: "gebrochen", auxiliary: "haben", translation: "ламати" },
    { infinitive: "brennen", prateritum: "brannte", partizip2: "gebrannt", auxiliary: "haben", translation: "горіти" },
    { infinitive: "einfallen", prateritum: "fiel ein", partizip2: "eingefallen", auxiliary: "sein", translation: "спадати на думку" },
    { infinitive: "einladen", prateritum: "lud ein", partizip2: "eingeladen", auxiliary: "haben", translation: "запрошувати" },
    { infinitive: "einschlafen", prateritum: "schlif ein", partizip2: "eingeschlafen", auxiliary: "sein", translation: "засинати" },
    { infinitive: "einsteigen", prateritum: "stieg ein", partizip2: "eingestiegen", auxiliary: "sein", translation: "сідати в транспорт" },
    { infinitive: "einziehen", prateritum: "zog ein", partizip2: "eingezogen", auxiliary: "sein", translation: "в'їжджати (в квартиру)" },
    { infinitive: "entscheiden", prateritum: "entschied", partizip2: "entschieden", auxiliary: "haben", translation: "вирішувати" },
    { infinitive: "fernsehen", prateritum: "sah fern", partizip2: "ferngesehen", auxiliary: "haben", translation: "дивитися телевізор" },
    { infinitive: "gefallen", prateritum: "gefiel", partizip2: "gefallen", auxiliary: "haben", translation: "подобатися" },
    { infinitive: "geschehen", prateritum: "geschah", partizip2: "geschehen", auxiliary: "sein", translation: "відбуватися" },
    { infinitive: "gewinnen", prateritum: "gewann", partizip2: "gewonnen", auxiliary: "haben", translation: "вигравати" },
    { infinitive: "hängen", prateritum: "hing", partizip2: "gehängt / gehangen", auxiliary: "haben", translation: "висіти, вішати" },
    { infinitive: "heißen", prateritum: "hieß", partizip2: "geheißen", auxiliary: "haben", translation: "називатися" },
    { infinitive: "klingen", prateritum: "klang", partizip2: "geklungen", auxiliary: "haben", translation: "звучати" },
    { infinitive: "laden", prateritum: "lud", partizip2: "geladen", auxiliary: "haben", translation: "вантажити, заряджати" },
    { infinitive: "lassen", prateritum: "ließ", partizip2: "gelassen", auxiliary: "haben", translation: "дозволяти, залишати" },
    { infinitive: "leidtun", prateritum: "tat leid", partizip2: "leidgetan", auxiliary: "haben", translation: "шкодувати" },
    { infinitive: "leihen", prateritum: "lieh", partizip2: "geliehen", auxiliary: "haben", translation: "позичати" },
    { infinitive: "losfahren", prateritum: "fuhr los", partizip2: "losgefahren", auxiliary: "sein", translation: "рушати (в дорогу)" },
    { infinitive: "mitbringen", prateritum: "brachte mit", partizip2: "mitgebracht", auxiliary: "haben", translation: "приносити з собою" },
    { infinitive: "mitkommen", prateritum: "kam mit", partizip2: "mitgekommen", auxiliary: "sein", translation: "йти разом з кимось" },
    { infinitive: "mitnehmen", prateritum: "nahm mit", partizip2: "mitgenommen", auxiliary: "haben", translation: "брати з собою" },
    { infinitive: "mögen", prateritum: "mochte", partizip2: "gemocht", auxiliary: "haben", translation: "любити, хотіти" },
    { infinitive: "riechen", prateritum: "roch", partizip2: "gerochen", auxiliary: "haben", translation: "пахнути, нюхати" },
    { infinitive: "scheinen", prateritum: "schien", partizip2: "geschienen", auxiliary: "haben", translation: "світити, здаватися" },
    { infinitive: "schneiden", prateritum: "schnitt", partizip2: "geschnitten", auxiliary: "haben", translation: "різати" },
    { infinitive: "sinken", prateritum: "sank", partizip2: "gesunken", auxiliary: "sein", translation: "опускатися, падати" },
    { infinitive: "spazieren gehen", prateritum: "ging spazieren", partizip2: "spazieren gegangen", auxiliary: "sein", translation: "гуляти" },
    { infinitive: "stattfinden", prateritum: "fand statt", partizip2: "stattgefunden", auxiliary: "haben", translation: "відбуватися (про захід)" },
    { infinitive: "stehlen", prateritum: "stahl", partizip2: "gestohlen", auxiliary: "haben", translation: "красти" },
    { infinitive: "streiten", prateritum: "stritt", partizip2: "gestritten", auxiliary: "haben", translation: "сперечатися" },
    { infinitive: "teilnehmen", prateritum: "nahm teil", partizip2: "teilgenommen", auxiliary: "haben", translation: "брати участь" },
    { infinitive: "treiben", prateritum: "trieb", partizip2: "getrieben", auxiliary: "haben", translation: "займатися (спортом)" },
    { infinitive: "übertragen", prateritum: "übertrug", partizip2: "übertragen", auxiliary: "haben", translation: "переносити, транслювати" },
    { infinitive: "überweisen", prateritum: "überwies", partizip2: "überwiesen", auxiliary: "haben", translation: "перераховувати (гроші)" },
    { infinitive: "umsteigen", prateritum: "stieg um", partizip2: "umgestiegen", auxiliary: "sein", translation: "пересідати" },
    { infinitive: "umziehen", prateritum: "zog um", partizip2: "umgezogen", auxiliary: "sein", translation: "переїжджати, переодягатися" },
    { infinitive: "unterhalten", prateritum: "unterhielt", partizip2: "unterhalten", auxiliary: "haben", translation: "спілкуватися, розважатися" },
    { infinitive: "unternehmen", prateritum: "unternahm", partizip2: "unternommen", auxiliary: "haben", translation: "підприймати (щось)" },
    { infinitive: "unterschreiben", prateritum: "unterschrieb", partizip2: "unterschrieben", auxiliary: "haben", translation: "підписувати" },
    { infinitive: "verbringen", prateritum: "verbrachte", partizip2: "verbracht", auxiliary: "haben", translation: "проводити (час)" },
    { infinitive: "vergleichen", prateritum: "verglich", partizip2: "verglichen", auxiliary: "haben", translation: "порівнювати" },
    { infinitive: "verschieben", prateritum: "verschob", partizip2: "verschoben", auxiliary: "haben", translation: "переносити (час)" },
    { infinitive: "verschwinden", prateritum: "verschwand", partizip2: "verschwunden", auxiliary: "sein", translation: "зникати" },
    { infinitive: "versprechen", prateritum: "versprach", partizip2: "versprochen", auxiliary: "haben", translation: "обіцяти" },
    { infinitive: "vorschlagen", prateritum: "schlug vor", partizip2: "vorgeschlagen", auxiliary: "haben", translation: "пропонувати" },
    { infinitive: "vorstellen", prateritum: "stellte vor", partizip2: "vorgestellt", auxiliary: "haben", translation: "представляти" },
    { infinitive: "weggehen", prateritum: "ging weg", partizip2: "weggegangen", auxiliary: "sein", translation: "йти геть" },
    { infinitive: "wegwerfen", prateritum: "warf weg", partizip2: "weggewорfen", auxiliary: "haben", translation: "викидати" },
    { infinitive: "wehtun", prateritum: "tat weh", partizip2: "behgetan", auxiliary: "haben", translation: "боліти, завдавати болю" },
    { infinitive: "werfen", prateritum: "warf", partizip2: "geworfen", auxiliary: "haben", translation: "кидати" },
    { infinitive: "zurechtkommen", prateritum: "kam zurecht", partizip2: "zurechtgekommen", auxiliary: "sein", translation: "справлятися, ладнати" },
    { infinitive: "zurückkommen", prateritum: "kam zurück", partizip2: "zurückgekommen", auxiliary: "sein", translation: "повертатися" }
];