export const imperativData = [
  { infinitive: "beginnen", du: "beginne", ihr: "beginnt", Sie: "beginnen Sie", translation: "починати" },
  { infinitive: "bieten", du: "biete", ihr: "bietet", Sie: "bieten Sie", translation: "пропонувати" },
  { infinitive: "bitten", du: "bitte", ihr: "bittet", Sie: "bitten Sie", translation: "просити" },
  { infinitive: "bleiben", du: "bleib", ihr: "bleibt", Sie: "bleiben Sie", translation: "залишатися" },
  { infinitive: "bringen", du: "bring", ihr: "bringt", Sie: "bringen Sie", translation: "принести" },
  { infinitive: "denken", du: "denk", ihr: "denkt", Sie: "denken Sie", translation: "думати" },
  { infinitive: "essen", du: "iss", ihr: "esst", Sie: "essen Sie", translation: "їсти" },
  { infinitive: "fahren", du: "fahr", ihr: "fahrt", Sie: "fahren Sie", translation: "їхати" },
  { infinitive: "fallen", du: "fall", ihr: "fallt", Sie: "fallen Sie", translation: "падати" },
  { infinitive: "geben", du: "gib", ihr: "gebt", Sie: "geben Sie", translation: "давати" },
  { infinitive: "gehen", du: "geh", ihr: "geht", Sie: "gehen Sie", translation: "йти" },
  { infinitive: "haben", du: "hab", ihr: "habt", Sie: "haben Sie", translation: "мати" },
  { infinitive: "halten", du: "halt", ihr: "haltet", Sie: "halten Sie", translation: "тримати" },
  { infinitive: "helfen", du: "hilf", ihr: "helft", Sie: "helfen Sie", translation: "допомагати" },
  { infinitive: "kommen", du: "komm", ihr: "kommt", Sie: "kommen Sie", translation: "приходити" },
  { infinitive: "laufen", du: "lauf", ihr: "lauft", Sie: "laufen Sie", translation: "бігти" },
  { infinitive: "lesen", du: "lies", ihr: "lest", Sie: "lesen Sie", translation: "читати" },
  { infinitive: "nehmen", du: "nimm", ihr: "nehmt", Sie: "nehmen Sie", translation: "брати" },
  { infinitive: "rufen", du: "ruf", ihr: "ruft", Sie: "rufen Sie", translation: "кликати" },
  { infinitive: "schlafen", du: "schlaf", ihr: "schlaft", Sie: "schlafen Sie", translation: "спати" },
  { infinitive: "schließen", du: "schließ", ihr: "schließt", Sie: "schließen Sie", translation: "закривати" },
  { infinitive: "schreiben", du: "schreib", ihr: "schreibt", Sie: "schreiben Sie", translation: "писати" },
  { infinitive: "sehen", du: "sieh", ihr: "seht", Sie: "sehen Sie", translation: "бачити" },
  { infinitive: "sein", du: "sei", ihr: "seid", Sie: "seien Sie", translation: "бути" },
  { infinitive: "sprechen", du: "sprich", py: "sprecht", Sie: "sprechen Sie", translation: "розмовляти" },
  { infinitive: "stehen", du: "steh", ihr: "steht", Sie: "stehen Sie", translation: "стояти" },
  { infinitive: "trinken", du: "trink", ihr: "trinkt", Sie: "trinken Sie", translation: "пити" },
  { infinitive: "vergessen", du: "vergiss", ihr: "vergesst", Sie: "vergessen Sie", translation: "забувати" },
  { infinitive: "verstehen", du: "versteh", ihr: "versteht", Sie: "verstehen Sie", translation: "розуміти" },
  { infinitive: "waschen", du: "wasch", ihr: "wascht", Sie: "waschen Sie", translation: "мити" },
  { infinitive: "werden", du: "werde", ihr: "werdet", Sie: "werden Sie", translation: "ставати" },
  { infinitive: "aufstehen", du: "steh auf", ihr: "steht auf", Sie: "stehen Sie auf", translation: "вставати" },
  { infinitive: "anrufen", du: "ruf an", ihr: "ruft an", Sie: "rufen Sie an", translation: "дзвонити" },
  { infinitive: "mitkommen", du: "komm mit", ihr: "kommt mit", Sie: "kommen Sie mit", translation: "йти разом" },
  { infinitive: "einladen", du: "lad ein", ihr: "ladet ein", Sie: "laden Sie ein", translation: "запрошувати" }
];